name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main  # Cambia esta rama según tu flujo de trabajo
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    - name: Log in to ACR
      uses: azure/container-actions/login@v1
      with:
        login-server: ${{ secrets.AZURE_ACR_NAME }}.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/my-image:${{ github.sha }} .

    - name: Push Docker image to ACR
      run: |
        docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/my-image:${{ github.sha }}
